services:
  register-service:
    build: ./Register_Microservice
    container_name: register_service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  login-service:
    build: ./Login_Microservice
    container_name: login_service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}